### ISSUE TITLE
Adding content in German Plone site: ConstraintNotSatisfied: de_DE

### ISSUE THREAD

**Issue by juh2** [plone/Plone#3] opened 2015-08-28 15:13 UTC
Create a new plone site. Choose German as language of site. Try to create a news item in the news folder.

    Traceback (innermost last):
    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module plone.dexterity.browser.add, line 127, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 141, in update
    Module z3c.form.group, line 52, in update
    Module z3c.form.group, line 48, in updateWidgets
    Module z3c.form.field, line 277, in update
    Module z3c.form.browser.select, line 51, in update
    Module z3c.form.browser.widget, line 171, in update
    Module z3c.form.widget, line 221, in update
    Module z3c.form.widget, line 114, in update
    Module zope.schema._bootstrapfields, line 78, in __get__
    Module zope.schema._bootstrapfields, line 182, in validate
    Module zope.schema._field, line 389, in _validate
    ConstraintNotSatisfied: de_DE

**Comment by davilima6** [comment] 2015-08-28 15:35
Duplicate of plone/Products.CMFPlone#754

**Closed by davilima6** 2015-08-28 15:35 UTC
